Add more flex attention cases to benchmark. (#3928)
Add the flex attention shapes which is used by real model to benchmark
for tracking performance.

I commented out 4 cases for now for the reason:
1. There is not enough share local memory for the Triton kernel. 
- Append shapes of Deepseek-v3 (Nope)
- Decode shapes of Deepseek-v3 (Nope)
2. Flex Attention doesn't support such kind of shapes: Error:
LoweringException: ValueError: Number of shared query heads sharing the
same KV head must be power of 2.
- Decode shapes of Qwen2-7B
3. Triton kernel block shapes must be power of 2.
- Decode shapes of Phi3-mini-3.8B

We will investigate the first issue on Triton side later.

Signed-off-by: Lu,Chengjun <chengjun.lu@intel.com>