Fix spirv-dis build for PredicatedIOINTEL support
Remove the version check and always build spirv-dis from source
using commit 4c2ec2a0 which includes SPV_INTEL_predicated_io support
(KhronosGroup/SPIRV-Tools#6665).

Fix error below after upgrading DLE to 2026.0.0:
```
E   subprocess.CalledProcessError: Command '['/home/runner/.local/bin/spirv-dis', '/tmp/tmpsa8ey3op']' returned non-zero exit status 252.
----------------------------- Captured stderr call -----------------------------
error: 7: Invalid capability operand: 6257
```

Signed-off-by: Whitney Tsang <whitney.tsang@intel.com>