Fix Python argument parsing for pointer type (#370)
Format `K` were used to parse all pointer type arguments. It is valid
when an input pointer can be represented as unsigned long long, but fail
when it is `None`, e.g.,
`FAILED operators/test_blocksparse.py::test_softmax[16-256-False] -
TypeError: argument 19 must be int, not None`.
This PR changed to use format `O` to get a `PyObject*`, then check if
the argument is valid before "casting" it to `void*`.

A subset of `test_softmax` tests pass after this fix.

Signed-off-by: Whitney Tsang <whitney.tsang@intel.com>