Check errors before using l0 kernel pointer (#429)
Checks for stored runtime error before using l0 kernel call. I suppose
we could also check for a nullptr in the l0 kernel handle but it seems
redundant - an assert would be nice, but I did not see other c code
using asserts. I copied the additional lines around the GIL from
upstream nvidia backend - it appears that was added as part of a recent
bug fix.

After this call we are once again properly surfacing L0 errors:
``` 
FAILED test_core.py::test_locality[4-2048-64-sum] - RuntimeError: Triton Error [ZE]: 2013265944
```

Closes #428