[WIN] Fix `error C7555: use of designated initializers requires at least '/std:c++20'` (#4889)
Fixes #4890

Signed-off-by: Whitney Tsang <whitney.tsang@intel.com>