Cache Nvidia binaries (#1510)
To avoid a rate limit when downloading binaries required for nvidia
backend.
```
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```