[Build][Clang][C++17] Don't capture structured bindings in lambdas (#5952)
Clang complains, feature supported since C++20

```
error: captured structured bindings are a C++20 extension [-Werror,-Wc++20-extensions]
```